name: Insert into database

on:
  schedule:
    - cron: '0 0 * * *' # Run once per day at midnight UTC
  workflow_dispatch:

jobs:
  insert-into-database:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger database update via API
        run: |
          curl -X GET https://sqm-vs-btc.onrender.com/update-db
    
      - name: Delete old scheduled workflow runs
        uses: MajorScruffy/delete-old-workflow-runs@v0.3.0
        with:
          repository: ${{ github.repository }}
          workflow: ".github/workflows/insert_into_db.yml"
          older-than-seconds: 3600
          event: schedule
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}