name: Insert into database

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  insert-into-database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Use Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install dependencies
        run: pip install --upgrade pip && pip install -r requirements.txt

      - name: Insert record into Database
        run: python engin/insert_db.py
